export const LOAD_DATA_REQUEST="LOAD_DATA_REQUEST"
export const LOAD_DATA_SUCCESS="LOAD_DATA_SUCCESS"
export const LOAD_DATA_FAILURE="LOAD_DATA_FAILURE"


export const SET_VIDEOGAME_DETAIL="SET_VIDEOGAME_DETAIL"
export const SET_VIDEOGAME_FAILURE="SET_VIDEOGAME_FAILURE"
export const CLEAN_VIDEOGAME_DETAIL="CLEAN_VIDEOGAME_DETAIL"

export const LOAD_VIDEOGAME_REQUEST_BY_NAME="LOAD_VIDEOGAME_REQUEST_BY_NAME"
export const LOAD_VIDEOGAME_BY_NAME="LOAD_VIDEOGAME_BY_NAME"
export const LOAD_VIDEOGAME_BY_NAME_FAILURE="LOAD_VIDEOGAME_BY_NAME_FAILURE"

export const LOAD_VIDEOGAME_GENRES="LOAD_VIDEOGAME_GENRES"
export const LOAD_VIDEOGAME_GENRES_FAILURE="LOAD_VIDEOGAME_GENRES_FAILURE"
